<?php

return [
    'name'            => env('APP_NAME', 'СЭД DocV3'),
    'env'             => env('APP_ENV', 'production'),
    'debug'           => (bool) env('APP_DEBUG', false),
    'url'             => env('APP_URL', 'http://localhost'),
    'timezone'        => env('APP_TIMEZONE', 'UTC'),
    'locale'          => env('APP_LOCALE', 'ru'),
    'fallback_locale' => env('APP_FALLBACK_LOCALE', 'ru'),
    'faker_locale'    => env('APP_FAKER_LOCALE', 'ru_RU'),
    'cipher'          => 'AES-256-CBC',
    'key'             => env('APP_KEY'),
    'previous_keys'   => [],
    'maintenance'     => ['driver' => 'file'],
    'providers'       => Illuminate\Support\ServiceProvider::defaultProviders()->merge([
        App\Providers\AppServiceProvider::class,
    ])->toArray(),
    'aliases'         => [
        'App'     => Illuminate\Support\Facades\App::class,
        'Arr'     => Illuminate\Support\Arr::class,
        'Auth'    => Illuminate\Support\Facades\Auth::class,
        'Cache'   => Illuminate\Support\Facades\Cache::class,
        'Config'  => Illuminate\Support\Facades\Config::class,
        'DB'      => Illuminate\Support\Facades\DB::class,
        'Hash'    => Illuminate\Support\Facades\Hash::class,
        'Http'    => Illuminate\Support\Facades\Http::class,
        'Lang'    => Illuminate\Support\Facades\Lang::class,
        'Log'     => Illuminate\Support\Facades\Log::class,
        'Redirect'=> Illuminate\Support\Facades\Redirect::class,
        'Request' => Illuminate\Support\Facades\Request::class,
        'Response'=> Illuminate\Support\Facades\Response::class,
        'Route'   => Illuminate\Support\Facades\Route::class,
        'Schema'  => Illuminate\Support\Facades\Schema::class,
        'Session' => Illuminate\Support\Facades\Session::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'Str'     => Illuminate\Support\Str::class,
        'URL'     => Illuminate\Support\Facades\URL::class,
        'Validator'=> Illuminate\Support\Facades\Validator::class,
        'View'    => Illuminate\Support\Facades\View::class,
    ],
];
